import type { Metadata } from "next";
import { Provider as JotaiProvider } from "jotai";
import "./globals.css";
import "./tiptap.css";
import "./headermenu.css";

import { Inter } from 'next/font/google';
import { Toaster } from "sonner";
import TailwindSizeMarker from "./components/dev/TailwindSizeMarker";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="bg-black">
      <JotaiProvider>
        <body
          className={`${inter.className} antialiased h-screen flex flex-col overflow-hidden rounded-lg bg-white`}
        >
          <Toaster richColors position="top-right" />
          <div className="flex-1 flex overflow-hidden">
            {children}
          </div>
          <TailwindSizeMarker />
        </body>
      </JotaiProvider>
    </html>
  );
}
