import type { Metadata } from "next";
import { Provider as JotaiProvider } from "jotai";
import "./globals.css";

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <JotaiProvider>
        <body
          className={`${inter.className} antialiased`}
        >
          {children}
        </body>
      </JotaiProvider>
    </html>
  );
}
